const STORE_KEY='telmo_partilhas_data_v1';
const defaults={
  settings:{siteName:'Telmo Partilhas',logo:'assets/logo.png',email:'telmo@example.com',instagram:'#',facebook:'#',location:'Portugal',password:'admin123'},
  texts:{heroTitle:'O RALLYCROSS ATRAVÉS DA MINHA LENTE',heroSubtitle:'Fotografia de Rallycross, Motorsport e momentos que ficam para a história.',aboutTitle:'SOBRE O MEU TRABALHO',aboutText:'Telmo Partilhas acompanha provas, pilotos, equipas e eventos de Motorsport através da fotografia, procurando a velocidade, a emoção e os detalhes que tornam cada prova única.',contactText:'Para cobertura fotográfica, parcerias, media ou colaboração, entra em contacto.'},
  stats:{races:0,photos:0,events:0,partners:0},races:[],photos:[],partners:[],news:[],results:[],messages:[]
};
function clone(v){return JSON.parse(JSON.stringify(v))}
let memoryStore={};
function storageGet(key){try{return window.localStorage.getItem(key)}catch(e){return memoryStore[key]??null}}
function storageSet(key,value){try{window.localStorage.setItem(key,value)}catch(e){memoryStore[key]=value}}
function sessionGet(key){try{return window.sessionStorage.getItem(key)}catch(e){return memoryStore['session:'+key]??null}}
function sessionSet(key,value){try{window.sessionStorage.setItem(key,value)}catch(e){memoryStore['session:'+key]=value}}
function sessionRemove(key){try{window.sessionStorage.removeItem(key)}catch(e){delete memoryStore['session:'+key]}}
function loadData(){try{const raw=storageGet(STORE_KEY);if(!raw)return clone(defaults);const saved=JSON.parse(raw)||{};return { ...clone(defaults), ...saved, settings:{...clone(defaults.settings),...(saved.settings||{})}, texts:{...clone(defaults.texts),...(saved.texts||{})}, stats:{...clone(defaults.stats),...(saved.stats||{})}, races:Array.isArray(saved.races)?saved.races:[], photos:Array.isArray(saved.photos)?saved.photos:[], partners:Array.isArray(saved.partners)?saved.partners:[], news:Array.isArray(saved.news)?saved.news:[], results:Array.isArray(saved.results)?saved.results:[], messages:Array.isArray(saved.messages)?saved.messages:[] }}catch(e){return clone(defaults)}}
let data=loadData();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(d+'T12:00:00'));
function save(msg='Guardado localmente'){storageSet(STORE_KEY,JSON.stringify(data));$('#saveIndicator').textContent=msg;showToast(msg)}
function showToast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1500)}
function uid(prefix){return prefix+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function imageField(name,value=''){return `<div class="field full"><label>${name}<input id="fieldImage" type="text" value="${esc(value)}" placeholder="Caminho local, ex.: assets/foto.jpg"></label><small style="color:#666">Para ficheiros escolhidos no computador, o browser guarda o ficheiro como base64 localmente. A opção abaixo faz isso automaticamente.</small><input id="imageFile" type="file" accept="image/*"></div>`}
function fileToDataURL(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(file)})}
function setActive(view){$$('.admin-view').forEach(v=>v.hidden=v.id!=='view-'+view);$$('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#viewTitle').textContent={dashboard:'Dashboard',content:'Conteúdo',photos:'Fotografias',calendar:'Calendário',results:'Resultados',partners:'Parceiros',news:'Notícias',contact:'Contactos',social:'Redes Sociais',settings:'Configurações'}[view]||view;render(view)}
function render(view){({dashboard:renderDashboard,content:renderContent,photos:renderPhotos,calendar:renderCalendar,results:renderResults,partners:renderPartners,news:renderNews,contact:renderContact,social:renderSocial,settings:renderSettings}[view])()}
function renderDashboard(){
  const stats=[['Fotografias',data.photos.length],['Provas',data.races.length],['Parceiros',data.partners.filter(p=>p.active).length],['Notícias',data.news.filter(n=>n.published).length],['Mensagens',data.messages.length]];
  const next=data.races.slice().sort((a,b)=>a.date.localeCompare(b.date))[0];
  const cats={};data.photos.forEach(p=>cats[p.category]=(cats[p.category]||0)+1);
  $('#view-dashboard').innerHTML=`<div class="grid-cards">${stats.map(x=>`<div class="metric"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div>
  <div class="two-col" style="margin-top:16px"><div class="panel"><h2>Próxima prova</h2><p style="font:700 28px 'Barlow Condensed';margin:0">${esc(next?.name||'Sem provas')}</p><p style="color:#777">${next?fmt(next.date)+' • '+esc(next.location):''}</p></div>
  <div class="panel"><h2>Atividade</h2><div class="chips"><span class="chip">Última gravação: ${new Date().toLocaleString('pt-PT')}</span><span class="chip">Dados no LocalStorage</span></div></div></div>
  <div class="panel"><h2>Fotografias por categoria</h2><div class="chart">${Object.entries(cats).map(([k,v])=>`<div class="bar" style="height:${Math.max(12,(v/Math.max(...Object.values(cats)))*180)}px"><span>${esc(k)}</span></div>`).join('')||'<div class="empty">Ainda sem fotografias.</div>'}</div></div>
  <div class="panel"><h2>Últimas mensagens</h2>${data.messages.slice(-5).reverse().map(m=>`<div style="padding:12px 0;border-bottom:1px solid #222"><strong>${esc(m.name)}</strong> — ${esc(m.subject)}<div style="color:#666;font-size:10px">${esc(m.email)} • ${new Date(m.date).toLocaleString('pt-PT')}</div><div style="color:#aaa;margin-top:6px">${esc(m.message)}</div></div>`).join('')||'<div class="empty">Sem mensagens.</div>'}</div>`
}
function renderContent(){
  const t=data.texts,s=data.stats;
  $('#view-content').innerHTML=`<div class="panel"><h2>Textos do website</h2><form id="contentForm" class="form-grid">
  ${[['heroTitle','Hero Title'],['heroSubtitle','Hero Subtitle'],['aboutTitle','About Título'],['aboutText','About Texto'],['contactText','Contact Texto']].map(([k,l])=>`<div class="field ${k.includes('Text')||k.includes('Subtitle')||k==='heroTitle'?'full':''}"><label>${l}<textarea name="${k}">${esc(t[k]||'')}</textarea></label></div>`).join('')}
  <div class="field"><label>Provas acompanhadas<input name="races" type="number" value="${data.stats.races||0}"></label></div><div class="field"><label>Fotografias<input name="photos" type="number" value="${data.stats.photos||0}"></label></div><div class="field"><label>Eventos<input name="events" type="number" value="${data.stats.events||0}"></label></div><div class="field"><label>Parceiros<input name="partners" type="number" value="${data.stats.partners||0}"></label></div>
  <div class="field full"><button class="admin-btn primary">GUARDAR ALTERAÇÕES</button></div></form></div>`
  $('#contentForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);['heroTitle','heroSubtitle','aboutTitle','aboutText','contactText'].forEach(k=>data.texts[k]=f.get(k));['races','photos','events','partners'].forEach(k=>data.stats[k]=Number(f.get(k)||0));save();alert('Atualizado. Abre index.html para ver.')}
}
let editId=null;
function renderPhotos(){
  $('#view-photos').innerHTML=`<div class="toolbar"><h2 style="font:700 32px 'Barlow Condensed';margin:0">FOTOGRAFIAS</h2><button class="admin-btn primary" id="addPhoto">+ ADICIONAR</button></div><div id="photoEditor"></div><div class="preview-grid">${data.photos.sort((a,b)=>(a.order||0)-(b.order||0)).map(p=>`<div class="preview-card"><img src="${esc(p.image||'assets/placeholder-rally.svg')}"><div class="pcopy"><strong>${esc(p.title)}</strong><small>${esc(p.category)} • ${p.featured?'DESTAQUE':''}</small><div style="display:flex;gap:6px;margin-top:9px"><button class="admin-btn" data-edit-photo="${p.id}">EDITAR</button><button class="admin-btn danger" data-del-photo="${p.id}">APAGAR</button></div></div></div>`).join('')||'<div class="empty">Sem fotografias.</div>'}</div>`
  $('#addPhoto').onclick=()=>photoForm();$$('[data-edit-photo]').forEach(b=>b.onclick=()=>photoForm(b.dataset.editPhoto));$$('[data-del-photo]').forEach(b=>b.onclick=()=>{if(confirm('Apagar fotografia?')){data.photos=data.photos.filter(p=>p.id!==b.dataset.delPhoto);save();renderPhotos()}})
}
function photoForm(id){
  const p=id?data.photos.find(x=>x.id===id):{id:uid('p'),title:'',category:'Rallycross',event:'',driver:'',date:'',location:'',description:'',image:'',featured:false,order:data.photos.length+1};editId=id||p.id;
  $('#photoEditor').innerHTML=`<div class="panel"><h3>${id?'Editar':'Adicionar'} fotografia</h3><form id="photoForm" class="form-grid">
  <div class="field"><label>Título<input name="title" value="${esc(p.title)}" required></label></div><div class="field"><label>Categoria<select name="category">${['Rallycross','Motorsport','Eventos','Pilotos','Equipas','Circuitos','Backstage','Destaques'].map(v=>`<option ${p.category===v?'selected':''}>${v}</option>`).join('')}</select></label></div>
  <div class="field"><label>Evento<input name="event" value="${esc(p.event)}"></label></div><div class="field"><label>Piloto / Equipa<input name="driver" value="${esc(p.driver)}"></label></div>
  <div class="field"><label>Data<input name="date" type="date" value="${esc(p.date)}"></label></div><div class="field"><label>Localização<input name="location" value="${esc(p.location)}"></label></div>
  <div class="field"><label>Ordem<input name="order" type="number" value="${p.order||1}"></label></div><label class="toggle"><input name="featured" type="checkbox" ${p.featured?'checked':''}> Shot of the Week</label>
  <div class="field full"><label>Descrição<textarea name="description">${esc(p.description)}</textarea></label></div>
  ${imageField('Imagem',p.image)}
  <div class="field full"><button class="admin-btn primary">GUARDAR FOTOGRAFIA</button> <button type="button" class="admin-btn" id="cancelEdit">CANCELAR</button></div></form><img class="preview-img" id="photoPreview" src="${esc(p.image||'assets/placeholder-rally.svg')}" alt=""></div>`;
  $('#cancelEdit').onclick=()=>$('#photoEditor').innerHTML='';
  $('#imageFile').onchange=async e=>{const f=e.target.files[0];if(f){const url=await fileToDataURL(f);$('#fieldImage').value=url;$('#photoPreview').src=url}}
  $('#fieldImage').oninput=e=>$('#photoPreview').src=e.target.value||'assets/placeholder-rally.svg';
  $('#photoForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);const obj={id:p.id,title:f.get('title'),category:f.get('category'),event:f.get('event'),driver:f.get('driver'),date:f.get('date'),location:f.get('location'),description:f.get('description'),image:f.get('fieldImage')||p.image,featured:f.get('featured')==='on',order:Number(f.get('order')||1)};const idx=data.photos.findIndex(x=>x.id===p.id);if(idx>=0)data.photos[idx]=obj;else data.photos.push(obj);save();renderPhotos()}
}
function renderCalendar(){
  $('#view-calendar').innerHTML=`<div class="toolbar"><h2 style="font:700 32px 'Barlow Condensed';margin:0">PROVAS / CALENDÁRIO</h2><button class="admin-btn primary" id="addRace">+ NOVA PROVA</button></div><div id="raceEditor"></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>DATA</th><th>PROVA</th><th>LOCAL</th><th>CATEGORIA</th><th>ESTADO</th><th>AÇÕES</th></tr></thead><tbody>${data.races.sort((a,b)=>a.date.localeCompare(b.date)).map(r=>`<tr><td>${fmt(r.date)}</td><td>${esc(r.name)}</td><td>${esc(r.location)}</td><td>${esc(r.category)}</td><td>${esc(r.status)}</td><td><button class="admin-btn" data-edit-race="${r.id}">EDITAR</button> <button class="admin-btn" data-dup-race="${r.id}">DUPLICAR</button> <button class="admin-btn danger" data-del-race="${r.id}">APAGAR</button></td></tr>`).join('')}</tbody></table></div>`
  $('#addRace').onclick=()=>raceForm();$$('[data-edit-race]').forEach(b=>b.onclick=()=>raceForm(b.dataset.editRace));$$('[data-dup-race]').forEach(b=>b.onclick=()=>{const r=clone(data.races.find(x=>x.id===b.dataset.dupRace));r.id=uid('r');r.name+=' (CÓPIA)';data.races.push(r);save();renderCalendar()});$$('[data-del-race]').forEach(b=>b.onclick=()=>{if(confirm('Apagar prova?')){data.races=data.races.filter(r=>r.id!==b.dataset.delRace);save();renderCalendar()}})
}
function raceForm(id){
  const r=id?data.races.find(x=>x.id===id):{id:uid('r'),name:'',date:'',endDate:'',location:'',circuit:'',country:'Portugal',category:'',status:'next',image:'assets/placeholder-rally.svg',description:'',link:'',result:''};
  $('#raceEditor').innerHTML=`<div class="panel"><h3>${id?'Editar':'Criar'} prova</h3><form id="raceForm" class="form-grid">
  <div class="field"><label>Nome<input name="name" value="${esc(r.name)}" required></label></div><div class="field"><label>Data<input name="date" type="date" value="${esc(r.date)}" required></label></div><div class="field"><label>Data final<input name="endDate" type="date" value="${esc(r.endDate||r.date)}"></label></div><div class="field"><label>Local<input name="location" value="${esc(r.location)}"></label></div><div class="field"><label>Circuito<input name="circuit" value="${esc(r.circuit)}"></label></div><div class="field"><label>País<input name="country" value="${esc(r.country)}"></label></div><div class="field"><label>Categoria<input name="category" value="${esc(r.category)}"></label></div><div class="field"><label>Estado<select name="status">${['next','upcoming','featured','done'].map(v=>`<option ${r.status===v?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="field"><label>Link<input name="link" value="${esc(r.link)}"></label></div><div class="field"><label>Resultado<input name="result" value="${esc(r.result)}"></label></div><div class="field full"><label>Descrição<textarea name="description">${esc(r.description)}</textarea></label></div>${imageField('Imagem',r.image)}<div class="field full"><button class="admin-btn primary">GUARDAR PROVA</button> <button type="button" class="admin-btn" id="cancelRace">CANCELAR</button></div></form><img class="preview-img" id="racePreview" src="${esc(r.image||'assets/placeholder-rally.svg')}"></div>`;
  $('#cancelRace').onclick=()=>$('#raceEditor').innerHTML='';$('#imageFile').onchange=async e=>{const f=e.target.files[0];if(f){const u=await fileToDataURL(f);$('#fieldImage').value=u;$('#racePreview').src=u}};$('#fieldImage').oninput=e=>$('#racePreview').src=e.target.value||'assets/placeholder-rally.svg';
  $('#raceForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);const o={...r,name:f.get('name'),date:f.get('date'),endDate:f.get('endDate'),location:f.get('location'),circuit:f.get('circuit'),country:f.get('country'),category:f.get('category'),status:f.get('status'),link:f.get('link'),result:f.get('result'),description:f.get('description'),image:f.get('fieldImage')||r.image};const i=data.races.findIndex(x=>x.id===r.id);if(i>=0)data.races[i]=o;else data.races.push(o);save();renderCalendar()}
}
function renderResults(){ $('#view-results').innerHTML=`<div class="toolbar"><h2 style="font:700 32px 'Barlow Condensed';margin:0">RESULTADOS</h2><button class="admin-btn primary" id="addResult">+ NOVO RESULTADO</button></div><div id="resultEditor"></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>PROVA</th><th>DATA</th><th>PILOTO</th><th>CATEGORIA</th><th>POS.</th><th>ACÇÕES</th></tr></thead><tbody>${data.results.map(r=>`<tr><td>${esc(r.race)}</td><td>${fmt(r.date)}</td><td>${esc(r.driver)}</td><td>${esc(r.category)}</td><td>${esc(r.position)}</td><td><button class="admin-btn" data-edit-result="${r.id}">EDITAR</button> <button class="admin-btn danger" data-del-result="${r.id}">APAGAR</button></td></tr>`).join('')}</tbody></table></div>`;$('#addResult').onclick=()=>resultForm();$$('[data-edit-result]').forEach(b=>b.onclick=()=>resultForm(b.dataset.editResult));$$('[data-del-result]').forEach(b=>b.onclick=()=>{if(confirm('Apagar resultado?')){data.results=data.results.filter(x=>x.id!==b.dataset.delResult);save();renderResults()}})}
function resultForm(id){
  const r=id?data.results.find(x=>x.id===id):{id:uid('res'),race:'',date:'',driver:'',category:'',position:'',time:'',notes:''};
  $('#resultEditor').innerHTML=`<div class="panel"><form id="resultForm" class="form-grid">
    <div class="field"><label>Prova<input name="race" value="${esc(r.race||'')}"></label></div>
    <div class="field"><label>Data<input name="date" type="date" value="${esc(r.date||'')}"></label></div>
    <div class="field"><label>Piloto<input name="driver" value="${esc(r.driver||'')}"></label></div>
    <div class="field"><label>Categoria<input name="category" value="${esc(r.category||'')}"></label></div>
    <div class="field"><label>Posição<input name="position" value="${esc(r.position||'')}"></label></div>
    <div class="field"><label>Tempo<input name="time" value="${esc(r.time||'')}"></label></div>
    <div class="field full"><label>Observações<textarea name="notes">${esc(r.notes||'')}</textarea></label></div>
    <div class="field full"><button class="admin-btn primary">GUARDAR</button></div>
  </form></div>`;
  $('#resultForm').onsubmit=e=>{
    e.preventDefault();
    const f=new FormData(e.currentTarget),o={...r};
    for(const [k,v] of f.entries())o[k]=v;
    const i=data.results.findIndex(x=>x.id===r.id);
    if(i>=0)data.results[i]=o;else data.results.push(o);
    save();renderResults();
  }
}
function renderPartners(){ $('#view-partners').innerHTML=`<div class="toolbar"><h2 style="font:700 32px 'Barlow Condensed';margin:0">PARCEIROS</h2><button class="admin-btn primary" id="addPartner">+ NOVO PARCEIRO</button></div><div id="partnerEditor"></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>LOGO</th><th>NOME</th><th>CATEGORIA</th><th>ORDEM</th><th>ATIVO</th><th>AÇÕES</th></tr></thead><tbody>${data.partners.sort((a,b)=>(a.order||0)-(b.order||0)).map(p=>`<tr><td><img class="thumb" src="${esc(p.logo||'assets/logo.png')}"></td><td>${esc(p.name)}</td><td>${esc(p.category)}</td><td>${p.order}</td><td>${p.active?'SIM':'NÃO'}</td><td><button class="admin-btn" data-edit-partner="${p.id}">EDITAR</button> <button class="admin-btn danger" data-del-partner="${p.id}">APAGAR</button></td></tr>`).join('')}</tbody></table></div>`;$('#addPartner').onclick=()=>partnerForm();$$('[data-edit-partner]').forEach(b=>b.onclick=()=>partnerForm(b.dataset.editPartner));$$('[data-del-partner]').forEach(b=>b.onclick=()=>{if(confirm('Apagar parceiro?')){data.partners=data.partners.filter(x=>x.id!==b.dataset.delPartner);save();renderPartners()}})}
function partnerForm(id){const p=id?data.partners.find(x=>x.id===id):{id:uid('pa'),name:'',logo:'',description:'',website:'',instagram:'',facebook:'',category:'OFFICIAL PARTNER',order:data.partners.length+1,active:true};$('#partnerEditor').innerHTML=`<div class="panel"><form id="partnerForm" class="form-grid"><div class="field"><label>Nome<input name="name" value="${esc(p.name)}"></label></div><div class="field"><label>Categoria<select name="category">${['MAIN PARTNER','OFFICIAL PARTNER','SUPPORTER'].map(x=>`<option ${p.category===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="field"><label>Website<input name="website" value="${esc(p.website)}"></label></div><div class="field"><label>Instagram<input name="instagram" value="${esc(p.instagram)}"></label></div><div class="field"><label>Facebook<input name="facebook" value="${esc(p.facebook)}"></label></div><div class="field"><label>Ordem<input name="order" type="number" value="${p.order||1}"></label></div><div class="field full"><label>Descrição<textarea name="description">${esc(p.description)}</textarea></label></div>${imageField('Logótipo',p.logo)}<label class="toggle"><input type="checkbox" name="active" ${p.active?'checked':''}> Ativo</label><div class="field full"><button class="admin-btn primary">GUARDAR PARCEIRO</button></div></form><img class="preview-img" id="partnerPreview" src="${esc(p.logo||'assets/logo.png')}"></div>`;$('#imageFile').onchange=async e=>{const f=e.target.files[0];if(f){const u=await fileToDataURL(f);$('#fieldImage').value=u;$('#partnerPreview').src=u}};$('#partnerForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),o={...p,name:f.get('name'),category:f.get('category'),website:f.get('website'),instagram:f.get('instagram'),facebook:f.get('facebook'),order:Number(f.get('order')||1),description:f.get('description'),logo:f.get('fieldImage')||p.logo,active:f.get('active')==='on'};const i=data.partners.findIndex(x=>x.id===p.id);if(i>=0)data.partners[i]=o;else data.partners.push(o);save();renderPartners()}}
function renderNews(){ $('#view-news').innerHTML=`<div class="toolbar"><h2 style="font:700 32px 'Barlow Condensed';margin:0">NOTÍCIAS</h2><button class="admin-btn primary" id="addNews">+ NOVA NOTÍCIA</button></div><div id="newsEditor"></div><div class="table-wrap"><table class="admin-table"><thead><tr><th>DATA</th><th>TÍTULO</th><th>CATEGORIA</th><th>PUBLICADO</th><th>AÇÕES</th></tr></thead><tbody>${data.news.sort((a,b)=>b.date.localeCompare(a.date)).map(n=>`<tr><td>${fmt(n.date)}</td><td>${esc(n.title)}</td><td>${esc(n.category)}</td><td>${n.published?'SIM':'NÃO'}</td><td><button class="admin-btn" data-edit-news="${n.id}">EDITAR</button> <button class="admin-btn danger" data-del-news="${n.id}">APAGAR</button></td></tr>`).join('')}</tbody></table></div>`;$('#addNews').onclick=()=>newsForm();$$('[data-edit-news]').forEach(b=>b.onclick=()=>newsForm(b.dataset.editNews));$$('[data-del-news]').forEach(b=>b.onclick=()=>{if(confirm('Apagar notícia?')){data.news=data.news.filter(x=>x.id!==b.dataset.delNews);save();renderNews()}})}
function newsForm(id){const n=id?data.news.find(x=>x.id===id):{id:uid('n'),title:'',summary:'',content:'',date:'',category:'Notícias',image:'',published:false};$('#newsEditor').innerHTML=`<div class="panel"><form id="newsForm" class="form-grid"><div class="field full"><label>Título<input name="title" value="${esc(n.title)}"></label></div><div class="field"><label>Data<input name="date" type="date" value="${esc(n.date)}"></label></div><div class="field"><label>Categoria<select name="category">${['Rallycross','Motorsport','Eventos','Fotografia','Parceiros','Notícias'].map(x=>`<option ${n.category===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="field full"><label>Resumo<textarea name="summary">${esc(n.summary)}</textarea></label></div><div class="field full"><label>Conteúdo<textarea name="content" style="min-height:180px">${esc(n.content)}</textarea></label></div>${imageField('Imagem',n.image)}<label class="toggle"><input type="checkbox" name="published" ${n.published?'checked':''}> Publicado</label><div class="field full"><button class="admin-btn primary">GUARDAR NOTÍCIA</button></div></form><img class="preview-img" id="newsPreview" src="${esc(n.image||'assets/placeholder-rally.svg')}"></div>`;$('#imageFile').onchange=async e=>{const f=e.target.files[0];if(f){const u=await fileToDataURL(f);$('#fieldImage').value=u;$('#newsPreview').src=u}};$('#newsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),o={...n,title:f.get('title'),date:f.get('date'),category:f.get('category'),summary:f.get('summary'),content:f.get('content'),image:f.get('fieldImage')||n.image,published:f.get('published')==='on'};const i=data.news.findIndex(x=>x.id===n.id);if(i>=0)data.news[i]=o;else data.news.push(o);save();renderNews()}}
function renderContact(){ $('#view-contact').innerHTML=`<div class="panel"><h2>Mensagens recebidas</h2>${data.messages.length?data.messages.slice().reverse().map(m=>`<div style="padding:15px 0;border-bottom:1px solid #222"><strong>${esc(m.name)}</strong> <span style="color:#666">(${esc(m.email)})</span><div style="font-size:10px;color:#777">${esc(m.subject)} • ${new Date(m.date).toLocaleString('pt-PT')}</div><p style="color:#aaa;line-height:1.6">${esc(m.message)}</p><button class="admin-btn danger" data-del-msg="${m.id}">APAGAR</button></div>`).join(''):'<div class="empty">Sem mensagens.</div>'}</div>`;$$('[data-del-msg]').forEach(b=>b.onclick=()=>{data.messages=data.messages.filter(m=>m.id!==b.dataset.delMsg);save();renderContact()})}
function renderSocial(){const s=data.settings;$('#view-social').innerHTML=`<div class="panel"><h2>Redes sociais</h2><form id="socialForm" class="form-grid"><div class="field"><label>Instagram<input name="instagram" value="${esc(s.instagram)}"></label></div><div class="field"><label>Facebook<input name="facebook" value="${esc(s.facebook)}"></label></div><div class="field"><label>Email<input name="email" value="${esc(s.email)}"></label></div><div class="field"><label>Localização<input name="location" value="${esc(s.location)}"></label></div><div class="field full"><button class="admin-btn primary">GUARDAR</button></div></form></div>`;$('#socialForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);Object.assign(data.settings,Object.fromEntries(f.entries()));save()}}
function renderSettings(){const s=data.settings;$('#view-settings').innerHTML=`<div class="panel"><h2>Configurações</h2><form id="settingsForm" class="form-grid"><div class="field"><label>Nome do site<input name="siteName" value="${esc(s.siteName)}"></label></div><div class="field"><label>Logótipo<input name="logo" value="${esc(s.logo)}"></label></div><div class="field full"><label>Nova palavra-passe<input name="password" type="password" placeholder="Deixa vazio para manter a atual"></label></div><div class="field full"><p style="color:#777;font-size:10px">Nota: num site HTML estático, esta autenticação serve como bloqueio local do painel, não como segurança de servidor.</p><button class="admin-btn primary">GUARDAR CONFIGURAÇÕES</button></div></form></div>`;$('#settingsForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);data.settings.siteName=f.get('siteName');data.settings.logo=f.get('logo');if(f.get('password'))data.settings.password=f.get('password');save()}}
function ensureData(){
  if(!storageGet(STORE_KEY)){
    const initial=clone(defaults);
    initial.races=[
      {id:uid('r'),name:'RALLYCROSS PORTUGAL',date:'2027-06-20',endDate:'2027-06-21',location:'Montalegre',circuit:'Circuito de Montalegre',country:'Portugal',category:'SuperCars',status:'next',image:'assets/placeholder-rally.svg',description:'Fim de semana de Rallycross em Montalegre.',link:'',result:''},
      {id:uid('r'),name:'MOTORSPORT FEST',date:'2027-07-11',endDate:'2027-07-11',location:'Lousada',circuit:'Circuito de Lousada',country:'Portugal',category:'Touring',status:'featured',image:'assets/placeholder-rally.svg',description:'Festival de Motorsport e ação em pista.',link:'',result:''},
      {id:uid('r'),name:'RALLYCROSS IBÉRICO',date:'2027-08-08',endDate:'2027-08-08',location:'Fafe',circuit:'Circuito de Fafe',country:'Portugal',category:'Super1600',status:'upcoming',image:'assets/placeholder-rally.svg',description:'Etapa do calendário ibérico.',link:'',result:''}
    ];
    initial.photos=[{id:uid('p'),title:'Ataque na curva',category:'Rallycross',event:'Rallycross Portugal',driver:'Piloto / Equipa',date:'2027-06-20',location:'Montalegre',description:'Imagem de exemplo.',image:'assets/placeholder-rally.svg',featured:true,order:1}];
    storageSet(STORE_KEY,JSON.stringify(initial));
  }
}
function start(){
  try{
    ensureData(); data=loadData();
    const form=$('#loginForm'), pass=$('#adminPassword');
    if(!form||!pass) throw new Error('Formulário de login não encontrado.');
    form.addEventListener('submit',e=>{
      e.preventDefault(); e.stopPropagation();
      const expected=String(data.settings?.password||'admin123');
      const entered=String(pass.value||'');
      if(entered===expected){
        sessionSet('tp_admin_ok','1');
        $('#loginView').hidden=true; $('#adminView').hidden=false; setActive('dashboard');
      }else{
        showToast('Palavra-passe incorreta');
        pass.focus(); pass.select();
      }
      return false;
    });
    $('#logoutBtn').onclick=()=>{sessionRemove('tp_admin_ok');location.reload()};
    $$('#adminNav button').forEach(b=>b.onclick=()=>setActive(b.dataset.view));
    if(sessionGet('tp_admin_ok')==='1'){$('#loginView').hidden=true;$('#adminView').hidden=false;setActive('dashboard')}
  }catch(err){
    console.error(err);
    const msg=document.createElement('div'); msg.style='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#4b1515;color:#fff;border:1px solid #8d2d2d;padding:12px 16px;font:12px Inter,Arial;z-index:9999'; msg.textContent='Erro ao iniciar o Admin: '+(err?.message||err); document.body.appendChild(msg);
  }
}
start();
