const SESSION = 'tp_admin';
const SESSION_TTL = 8 * 60 * 60 * 1000;
const MAX_JSON = 2_000_000;
const MAX_IMAGE = 15 * 1024 * 1024;
const MAX_VIDEO = 120 * 1024 * 1024;

const TABLES_SQL = [
  `CREATE TABLE IF NOT EXISTS site_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS site_stats (id TEXT PRIMARY KEY, sort_order INTEGER NOT NULL DEFAULT 0, value TEXT NOT NULL, label TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS gallery (id TEXT PRIMARY KEY, title TEXT NOT NULL, event TEXT NOT NULL, driver TEXT NOT NULL, date TEXT NOT NULL, location TEXT NOT NULL, category TEXT NOT NULL, image TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS races (id TEXT PRIMARY KEY, name TEXT NOT NULL, date TEXT NOT NULL, end_date TEXT NOT NULL DEFAULT '', location TEXT NOT NULL, circuit TEXT NOT NULL, country TEXT NOT NULL, category TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'done', image TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', result TEXT NOT NULL DEFAULT '', link TEXT NOT NULL DEFAULT '', sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS results (id TEXT PRIMARY KEY, race TEXT NOT NULL, date TEXT NOT NULL, driver TEXT NOT NULL, category TEXT NOT NULL, position TEXT NOT NULL, time TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS partners (id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, logo TEXT NOT NULL DEFAULT '', description TEXT NOT NULL DEFAULT '', website TEXT NOT NULL DEFAULT '', instagram TEXT NOT NULL DEFAULT '', facebook TEXT NOT NULL DEFAULT '', sort_order INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS news (id TEXT PRIMARY KEY, title TEXT NOT NULL, summary TEXT NOT NULL DEFAULT '', content TEXT NOT NULL DEFAULT '', date TEXT NOT NULL, category TEXT NOT NULL, image TEXT NOT NULL DEFAULT '', published INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS reviews (id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL DEFAULT '', rating INTEGER NOT NULL DEFAULT 5, text TEXT NOT NULL, approved INTEGER NOT NULL DEFAULT 0, featured INTEGER NOT NULL DEFAULT 0, date TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS media (id TEXT PRIMARY KEY, object_key TEXT UNIQUE NOT NULL, url TEXT NOT NULL, original_name TEXT NOT NULL, mime_type TEXT NOT NULL, media_type TEXT NOT NULL, size INTEGER NOT NULL, width INTEGER, height INTEGER, duration REAL, alt TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY, date TEXT NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, subject TEXT NOT NULL DEFAULT '', message TEXT NOT NULL, read INTEGER NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY, action TEXT NOT NULL, entity TEXT NOT NULL, entity_id TEXT, created_at TEXT NOT NULL)`
];

const SETTING_ALLOW = [
  'siteName','siteLogo','heroEyebrow','heroTitle','heroSubtitle','heroGalleryButton','heroCalendarButton','heroTags','marqueeText',
  'aboutKicker','aboutTitle','aboutLead','nextKicker','nextLive','calendarKicker','calendarTitle','calendarLead','galleryKicker','galleryTitle','galleryLead',
  'shotTitle','reviewsKicker','reviewsTitle','reviewsLead','partnersKicker','partnersTitle','partnersLead','newsKicker','newsTitle','newsLead','resultsKicker','resultsTitle','resultsLead',
  'contactsKicker','contactsTitle','contactsLead','collaborationKicker','collaborationTitle','collaborationLead','collaborationButton','socialsKicker','socialsTitle',
  'footer','footerRights','email','instagram','facebook','location','navHome','navAbout','navCalendar','navResults','navGallery','navPartners','navNews','navContacts','navGalleryCta',
  'heroVideo','heroFallbackImage','heroVideoEnabled','heroOverlay','heroVideoPoster','seoTitle','seoDescription','canonicalUrl','ogImage'
];
const ALLOWED_SETTINGS = new Set(SETTING_ALLOW);

function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra}})}
function cookieValue(request,name){const raw=request.headers.get('Cookie')||'';const hit=raw.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='));return hit?hit.slice(name.length+1):''}
function b64u(input){const bytes=typeof input==='string'?new TextEncoder().encode(input):input;let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function fromB64u(s){const base=s.replace(/-/g,'+').replace(/_/g,'/');const rem=base.length%4;const pad=rem?'='.repeat(4-rem):'';const binary=atob(base+pad),out=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)out[i]=binary.charCodeAt(i);return out}
async function hmac(secret,text){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(text)))}
async function makeSession(secret){const payload=`${Date.now()+SESSION_TTL}.${crypto.randomUUID()}`;return `${b64u(payload)}.${b64u(await hmac(secret,payload))}`}
async function isAdmin(request,env){const secret=env.ADMIN_PASSWORD;if(!secret)return false;const token=cookieValue(request,SESSION);if(!token)return false;const [payload64,sig]=token.split('.');if(!payload64||!sig)return false;let payload;try{payload=new TextDecoder().decode(fromB64u(payload64))}catch{return false}const [exp]=payload.split('.');if(!Number(exp)||Number(exp)<Date.now())return false;const expected=b64u(await hmac(secret,payload));if(expected.length!==sig.length)return false;let diff=0;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^sig.charCodeAt(i);return diff===0}
function sessionCookie(value,request,maxAge=SESSION_TTL/1000){const secure=new URL(request.url).protocol==='https:'?'; Secure':'';return `${SESSION}=${value}; Path=/; HttpOnly; SameSite=Lax${secure}; Max-Age=${Math.floor(maxAge)}`}
function clearSessionCookie(request){const secure=new URL(request.url).protocol==='https:'?'; Secure':'';return `${SESSION}=; Path=/; HttpOnly; SameSite=Lax${secure}; Max-Age=0`}
function safeOrigin(request){const origin=request.headers.get('Origin');return !origin||origin===new URL(request.url).origin}
function adminMutation(request){return safeOrigin(request)&&request.headers.get('X-TP-Admin')==='1'}
function text(v,max=5000){return String(v??'').trim().slice(0,max)}
function idValue(v,fallback){const s=text(v,120);return /^[A-Za-z0-9_-]+$/.test(s)?s:fallback}
function urlValue(v,{relative=true,data=false}={}){const s=text(v,2000);if(!s)return '';if(relative&&/^(assets|\/assets|api\/media|\/api\/media|\/)/.test(s))return s;if(data&&/^data:image\/(jpeg|png|webp);base64,/i.test(s))return s;try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.toString():''}catch{return ''}}
function emailValid(v){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(String(v||'').trim())}
function bool(v){return v===true||v===1||v==='1'||v==='true'}
function now(){return new Date().toISOString()}
function dateValid(v){return /^\d{4}-\d{2}-\d{2}$/.test(String(v||''))||!v}

async function ensureSchema(env){if(!env.DB)return false;for(const sql of TABLES_SQL)await env.DB.prepare(sql).run();return true}
async function migrateLegacy(env){try{const c=await env.DB.prepare('SELECT COUNT(*) c FROM site_settings').first();if(Number(c?.c||0)>0)return false;const old=await env.DB.prepare('SELECT data FROM app_state WHERE id=1').first();if(!old?.data)return false;return old.data}catch{return false}}

function normalize(input){const d=input&&typeof input==='object'?input:{};const s={};for(const k of SETTING_ALLOW)s[k]=text(d.settings?.[k],k==='heroTitle'||k==='heroSubtitle'||k.endsWith('Lead')||k.endsWith('Title')||k==='footer'?1200:2000);s.heroVideoEnabled=String(bool(d.settings?.heroVideoEnabled));s.heroOverlay=String(Math.min(.9,Math.max(0,Number(d.settings?.heroOverlay??.46))));
const stats=Array.isArray(d.stats)?d.stats.slice(0,20).map((x,i)=>({id:idValue(x?.id,`stat-${i+1}`),value:text(x?.value??x?.[0],80),label:text(x?.label??x?.[1],160),order:i})):[];
const gallery=Array.isArray(d.gallery)?d.gallery.slice(0,500).map((x,i)=>({id:idValue(x?.id,`g-${crypto.randomUUID().slice(0,8)}`),title:text(x?.title,200),event:text(x?.event,200),driver:text(x?.driver,150),date:text(x?.date,20),location:text(x?.location,200),category:text(x?.category,100),image:urlValue(x?.image,{relative:true,data:true}),description:text(x?.description,1500),order:Number.isFinite(Number(x?.order))?Number(x.order):i})):[];
const races=Array.isArray(d.races)?d.races.slice(0,250).map((x,i)=>({id:idValue(x?.id,`r-${crypto.randomUUID().slice(0,8)}`),name:text(x?.name,200),date:text(x?.date,20),endDate:text(x?.endDate,20),location:text(x?.location,200),circuit:text(x?.circuit,200),country:text(x?.country,100),category:text(x?.category,100),status:['next','featured','done'].includes(x?.status)?x.status:'done',image:urlValue(x?.image,{relative:true,data:true}),description:text(x?.description,1500),result:text(x?.result,200),link:urlValue(x?.link,{relative:false}),order:i})):[];
const results=Array.isArray(d.results)?d.results.slice(0,500).map(x=>({id:idValue(x?.id,`res-${crypto.randomUUID().slice(0,8)}`),race:text(x?.race,200),date:text(x?.date,20),driver:text(x?.driver,150),category:text(x?.category,100),position:text(x?.position,40),time:text(x?.time,60),notes:text(x?.notes,500)})):[];
const partners=Array.isArray(d.partners)?d.partners.slice(0,150).map((x,i)=>({id:idValue(x?.id,`p-${crypto.randomUUID().slice(0,8)}`),name:text(x?.name,200),category:text(x?.category,100),logo:urlValue(x?.logo,{relative:true,data:true}),description:text(x?.description,900),website:urlValue(x?.website,{relative:false}),instagram:urlValue(x?.instagram,{relative:false}),facebook:urlValue(x?.facebook,{relative:false}),order:Number.isFinite(Number(x?.order))?Number(x.order):i+1,active:x?.active!==false})):[];
const news=Array.isArray(d.news)?d.news.slice(0,250).map(x=>({id:idValue(x?.id,`n-${crypto.randomUUID().slice(0,8)}`),title:text(x?.title,250),summary:text(x?.summary,800),content:text(x?.content,6000),date:text(x?.date,20),category:text(x?.category,100),image:urlValue(x?.image,{relative:true,data:true}),published:x?.published!==false})):[];
const reviews=Array.isArray(d.reviews)?d.reviews.slice(0,500).map(x=>({id:idValue(x?.id,`rv-${crypto.randomUUID().slice(0,8)}`),name:text(x?.name,150),role:text(x?.role,150),rating:Math.min(5,Math.max(1,Number(x?.rating||5))),text:text(x?.text,1800),approved:bool(x?.approved),featured:bool(x?.featured),date:text(x?.date,40)||now()})):[];
return {settings:s,stats,gallery,races,results,partners,news,reviews,media:Array.isArray(d.media)?d.media.slice(0,1000):[],featuredGalleryId:idValue(d.featuredGalleryId,'')||''};}

async function writeState(env,input){const d=normalize(input), stamp=now();const stm=[];for(const t of ['site_settings','site_stats','gallery','races','results','partners','news','reviews'])stm.push(env.DB.prepare(`DELETE FROM ${t}`));for(const [k,v] of Object.entries(d.settings))if(ALLOWED_SETTINGS.has(k))stm.push(env.DB.prepare('INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,?)').bind(k,v,stamp));for(const x of d.stats)stm.push(env.DB.prepare('INSERT INTO site_stats(id,sort_order,value,label,updated_at) VALUES(?,?,?,?,?)').bind(x.id,x.order,x.value,x.label,stamp));for(const x of d.gallery)stm.push(env.DB.prepare('INSERT INTO gallery(id,title,event,driver,date,location,category,image,description,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(x.id,x.title,x.event,x.driver,x.date,x.location,x.category,x.image,x.description,x.order,stamp,stamp));for(const x of d.races)stm.push(env.DB.prepare('INSERT INTO races(id,name,date,end_date,location,circuit,country,category,status,image,description,result,link,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(x.id,x.name,x.date,x.endDate,x.location,x.circuit,x.country,x.category,x.status,x.image,x.description,x.result,x.link,x.order,stamp,stamp));for(const x of d.results)stm.push(env.DB.prepare('INSERT INTO results(id,race,date,driver,category,position,time,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(x.id,x.race,x.date,x.driver,x.category,x.position,x.time,x.notes,stamp,stamp));for(const x of d.partners)stm.push(env.DB.prepare('INSERT INTO partners(id,name,category,logo,description,website,instagram,facebook,sort_order,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(x.id,x.name,x.category,x.logo,x.description,x.website,x.instagram,x.facebook,x.order,x.active?1:0,stamp,stamp));for(const x of d.news)stm.push(env.DB.prepare('INSERT INTO news(id,title,summary,content,date,category,image,published,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(x.id,x.title,x.summary,x.content,x.date,x.category,x.image,x.published?1:0,stamp,stamp));for(const x of d.reviews)stm.push(env.DB.prepare('INSERT INTO reviews(id,name,role,rating,text,approved,featured,date,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(x.id,x.name,x.role,x.rating,x.text,x.approved?1:0,x.featured?1:0,x.date,stamp,stamp));stm.push(env.DB.prepare('INSERT INTO site_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind('featuredGalleryId',d.featuredGalleryId,stamp));for(let i=0;i<stm.length;i+=75)await env.DB.batch(stm.slice(i,i+75));return d}

async function readState(env, includePrivateReviews=false){const [settings,stats,gallery,races,results,partners,news,reviews,media]=await Promise.all([
 env.DB.prepare('SELECT key,value FROM site_settings').all(),env.DB.prepare('SELECT id,sort_order,value,label FROM site_stats ORDER BY sort_order,id').all(),env.DB.prepare('SELECT id,title,event,driver,date,location,category,image,description,sort_order FROM gallery ORDER BY sort_order,date DESC').all(),env.DB.prepare('SELECT id,name,date,end_date,location,circuit,country,category,status,image,description,result,link,sort_order FROM races ORDER BY date,sort_order').all(),env.DB.prepare('SELECT id,race,date,driver,category,position,time,notes FROM results ORDER BY date DESC').all(),env.DB.prepare('SELECT id,name,category,logo,description,website,instagram,facebook,sort_order,active FROM partners ORDER BY sort_order,id').all(),env.DB.prepare('SELECT id,title,summary,content,date,category,image,published FROM news ORDER BY date DESC').all(),env.DB.prepare('SELECT id,name,role,rating,text,approved,featured,date FROM reviews ORDER BY date DESC').all(),env.DB.prepare('SELECT id,object_key,url,original_name,mime_type,media_type,size,width,height,duration,alt,status,created_at,updated_at FROM media ORDER BY created_at DESC').all()
]);const s={};for(const r of settings.results||[])s[r.key]=r.value;const featuredGalleryId=s.featuredGalleryId||'';delete s.featuredGalleryId;return {settings:s,stats:(stats.results||[]).map(r=>({id:r.id,value:r.value,label:r.label,order:r.sort_order})),gallery:(gallery.results||[]).map(r=>({id:r.id,title:r.title,event:r.event,driver:r.driver,date:r.date,location:r.location,category:r.category,image:r.image,description:r.description,order:r.sort_order})),races:(races.results||[]).map(r=>({id:r.id,name:r.name,date:r.date,endDate:r.end_date,location:r.location,circuit:r.circuit,country:r.country,category:r.category,status:r.status,image:r.image,description:r.description,result:r.result,link:r.link,order:r.sort_order})),results:(results.results||[]).map(r=>({id:r.id,race:r.race,date:r.date,driver:r.driver,category:r.category,position:r.position,time:r.time,notes:r.notes})),partners:(partners.results||[]).map(r=>({id:r.id,name:r.name,category:r.category,logo:r.logo,description:r.description,website:r.website,instagram:r.instagram,facebook:r.facebook,order:r.sort_order,active:!!r.active})),news:(news.results||[]).map(r=>({id:r.id,title:r.title,summary:r.summary,content:r.content,date:r.date,category:r.category,image:r.image,published:!!r.published})),reviews:(reviews.results||[]).filter(r=>includePrivateReviews||r.approved).map(r=>({id:r.id,name:r.name,role:r.role,rating:Number(r.rating),text:r.text,approved:!!r.approved,featured:!!r.featured,date:r.date})),media:media.results||[],featuredGalleryId};}

function sniff(bytes,declared){const b=Array.from(new Uint8Array(bytes));const starts=a=>a.every((v,i)=>b[i]===v);if(starts([255,216,255]))return'image/jpeg';if(starts([137,80,78,71,13,10,26,10]))return'image/png';if(starts([71,73,70,56]))return'image/gif';if(b[0]===82&&b[1]===73&&b[2]===70&&b[3]===70&&b[8]===87&&b[9]===69&&b[10]===66&&b[11]===80)return'image/webp';if(b[0]===26&&b[1]===69&&b[2]===223&&b[3]===163)return'video/webm';if(b.length>=12&&b[4]===102&&b[5]===116&&b[6]===121&&b[7]===112)return'video/mp4';return declared}
function mediaType(m){return m.startsWith('video/')?'video':m.startsWith('image/')?'image':'other'}
function ext(m){return {'image/jpeg':'jpg','image/png':'png','image/gif':'gif','image/webp':'webp','video/mp4':'mp4','video/webm':'webm'}[m]||'bin'}

async function handleApi(request,env){const url=new URL(request.url),path=url.pathname;if(!path.startsWith('/api/'))return null;
if(path==='/api/health'&&request.method==='GET'){let d1=!!env.DB,tables=false,counts={};if(d1){try{await ensureSchema(env);tables=true;for(const t of ['gallery','races','results','partners','news','reviews','media','messages']){const r=await env.DB.prepare(`SELECT COUNT(*) c FROM ${t}`).first();counts[t]=Number(r?.c||0)}}catch{}}return json({ok:true,d1,tables,r2:!!env.MEDIA,adminPasswordConfigured:!!env.ADMIN_PASSWORD,counts})}
if(path==='/api/auth'&&request.method==='GET')return json({ok:await isAdmin(request,env)});
if(path==='/api/auth'&&request.method==='POST'){if(!env.ADMIN_PASSWORD)return json({ok:false,error:'O secret ADMIN_PASSWORD não está configurado na Cloudflare.'},503);let body;try{body=await request.json()}catch{return json({ok:false,error:'Pedido inválido.'},400)}if(String(body.password||'')!==String(env.ADMIN_PASSWORD))return json({ok:false,error:'Password incorreta.'},401);const token=await makeSession(env.ADMIN_PASSWORD);return json({ok:true},200,{'Set-Cookie':sessionCookie(token,request)})}
if(path==='/api/auth'&&request.method==='DELETE')return json({ok:true},200,{'Set-Cookie':clearSessionCookie(request)});
if(path==='/api/state'&&request.method==='GET'){if(!env.DB)return json({ok:false,error:'D1 não está ligado.'},503);try{await ensureSchema(env);const legacy=await migrateLegacy(env);if(legacy){await writeState(env,JSON.parse(legacy))}return json({ok:true,data:await readState(env,await isAdmin(request,env)),updatedAt:now()})}catch{return json({ok:false,error:'Falha ao ler a D1.'},500)}}
if(path==='/api/state'&&request.method==='PUT'){if(!(await isAdmin(request,env))||!adminMutation(request))return json({ok:false,error:'Não autorizado.'},401);if(!env.DB)return json({ok:false,error:'D1 não está ligado.'},503);let body;try{const raw=await request.text();if(raw.length>MAX_JSON)throw new Error('too-big');body=JSON.parse(raw)}catch(e){return json({ok:false,error:e.message==='too-big'?'Dados demasiado grandes.':'JSON inválido.'},400)}try{await ensureSchema(env);const d=await writeState(env,body);await env.DB.prepare('INSERT INTO audit_log(id,action,entity,entity_id,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),'save','state',null,now()).run();return json({ok:true,data:await readState(env),updatedAt:now()})}catch{return json({ok:false,error:'Não foi possível guardar os dados na D1.'},500)}}

if(path==='/api/reviews'&&request.method==='POST'){if(!env.DB||!safeOrigin(request))return json({ok:false,error:'Serviço indisponível.'},503);let body;try{body=await request.json()}catch{return json({ok:false,error:'JSON inválido.'},400)}if(body.website)return json({ok:false,error:'Pedido inválido.'},400);const name=text(body.name,120),role=text(body.role,120),review=text(body.text,1800),rating=Math.min(5,Math.max(1,Number(body.rating||5)));if(!name||!review||![1,2,3,4,5].includes(rating))return json({ok:false,error:'Preenche nome, avaliação e classificação.'},400);try{await ensureSchema(env);const id=crypto.randomUUID(),stamp=now();await env.DB.prepare('INSERT INTO reviews(id,name,role,rating,text,approved,featured,date,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,name,role,rating,review,0,0,stamp,stamp,stamp).run();return json({ok:true,id,message:'A tua review foi enviada e ficará pendente de aprovação.'})}catch{return json({ok:false,error:'Não foi possível enviar a review.'},500)}}
if(path==='/api/messages'&&request.method==='POST'){if(!env.DB||!safeOrigin(request))return json({ok:false,error:'Serviço indisponível.'},503);let body;try{body=await request.json()}catch{return json({ok:false,error:'JSON inválido.'},400)}const name=text(body.name,120),mail=text(body.email,180),subject=text(body.subject,200),message=text(body.message,5000);if(!name||!emailValid(mail)||!message)return json({ok:false,error:'Preenche nome, email válido e mensagem.'},400);try{await ensureSchema(env);const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO messages(id,date,name,email,subject,message,read) VALUES(?,?,?,?,?,?,0)').bind(id,now(),name,mail,subject,message).run();return json({ok:true,id})}catch{return json({ok:false,error:'Não foi possível enviar a mensagem.'},500)}}
if(path==='/api/messages'&&request.method==='GET'){if(!(await isAdmin(request,env)))return json({ok:false,error:'Não autorizado.'},401);if(!env.DB)return json({ok:false,error:'D1 não está ligado.'},503);await ensureSchema(env);const {results}=await env.DB.prepare('SELECT id,date,name,email,subject,message,read FROM messages ORDER BY date DESC').all();return json({ok:true,messages:results||[]})}
if(path==='/api/messages'&&request.method==='PATCH'){if(!(await isAdmin(request,env))||!adminMutation(request))return json({ok:false,error:'Não autorizado.'},401);let body;try{body=await request.json()}catch{return json({ok:false,error:'JSON inválido.'},400)}if(!body.id)return json({ok:false,error:'ID em falta.'},400);await env.DB.prepare('UPDATE messages SET read=? WHERE id=?').bind(bool(body.read)?1:0,text(body.id,120)).run();return json({ok:true})}
if(path==='/api/messages'&&request.method==='DELETE'){if(!(await isAdmin(request,env))||!adminMutation(request))return json({ok:false,error:'Não autorizado.'},401);await env.DB.prepare('DELETE FROM messages').run();return json({ok:true})}
if(path==='/api/media'&&request.method==='POST'){if(!(await isAdmin(request,env))||!adminMutation(request))return json({ok:false,error:'Não autorizado.'},401);if(!env.MEDIA)return json({ok:false,error:'R2 não está ligado. Configure o binding MEDIA.'},503);const form=await request.formData(),file=form.get('file');if(!(file instanceof File))return json({ok:false,error:'Ficheiro em falta.'},400);const declared=text(file.type,100),kind=mediaType(declared);if(!['image','video'].includes(kind))return json({ok:false,error:'Use JPG, PNG, WEBP, MP4 ou WEBM.'},415);const limit=kind==='video'?MAX_VIDEO:MAX_IMAGE;if(file.size>limit)return json({ok:false,error:`O ficheiro ultrapassa o limite de ${kind==='video'?'120 MB':'15 MB'}.`},413);const magic=sniff(await file.slice(0,16).arrayBuffer(),declared);if(mediaType(magic)!==kind)return json({ok:false,error:'O conteúdo do ficheiro não corresponde ao tipo declarado.'},415);if(!['image/jpeg','image/png','image/gif','image/webp','video/mp4','video/webm'].includes(magic))return json({ok:false,error:'Formato não autorizado.'},415);const id=crypto.randomUUID(),key=`uploads/${new Date().toISOString().slice(0,10)}/${id}.${ext(magic)}`,stamp=now();try{await env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:magic,cacheControl:'public, max-age=31536000, immutable'}});await ensureSchema(env);const urlOut=`/api/media/${id}`;await env.DB.prepare('INSERT INTO media(id,object_key,url,original_name,mime_type,media_type,size,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,key,urlOut,text(file.name,255),magic,kind,file.size,'active',stamp,stamp).run();return json({ok:true,media:{id,key,url:urlOut,original_name:file.name,mime_type:magic,media_type:kind,size:file.size}})}catch{try{await env.MEDIA.delete(key)}catch{}return json({ok:false,error:'Não foi possível guardar o ficheiro.'},500)}}
const mm=path.match(/^\/api\/media\/([^/]+)$/);if(mm&&request.method==='GET'){if(!env.MEDIA||!env.DB)return new Response('Storage indisponível',{status:503});const id=text(mm[1],120),row=await env.DB.prepare("SELECT object_key FROM media WHERE id=? AND status='active'").bind(id).first();if(!row)return new Response('Not found',{status:404});const obj=await env.MEDIA.get(row.object_key);if(!obj)return new Response('Not found',{status:404});const h=new Headers();obj.writeHttpMetadata(h);h.set('ETag',obj.httpEtag);h.set('Cache-Control','public, max-age=31536000, immutable');return new Response(obj.body,{headers:h})}
if(path==='/api/media'&&request.method==='DELETE'){if(!(await isAdmin(request,env))||!adminMutation(request))return json({ok:false,error:'Não autorizado.'},401);if(!env.DB)return json({ok:false,error:'D1 não está ligado.'},503);const id=text(url.searchParams.get('id'),120);if(!id)return json({ok:false,error:'ID em falta.'},400);const row=await env.DB.prepare('SELECT object_key FROM media WHERE id=?').bind(id).first();if(!row)return json({ok:false,error:'Ficheiro não encontrado.'},404);const refs=await Promise.all([env.DB.prepare('SELECT COUNT(*) c FROM gallery WHERE image=(SELECT url FROM media WHERE id=?)').bind(id).first(),env.DB.prepare('SELECT COUNT(*) c FROM races WHERE image=(SELECT url FROM media WHERE id=?)').bind(id).first(),env.DB.prepare('SELECT COUNT(*) c FROM partners WHERE logo=(SELECT url FROM media WHERE id=?)').bind(id).first(),env.DB.prepare('SELECT COUNT(*) c FROM news WHERE image=(SELECT url FROM media WHERE id=?)').bind(id).first(),env.DB.prepare('SELECT COUNT(*) c FROM site_settings WHERE value=(SELECT url FROM media WHERE id=?)').bind(id).first()]);if(refs.some(x=>Number(x?.c||0)>0))return json({ok:false,error:'Este ficheiro está a ser usado pelo site. Substitui a referência antes de o apagar.'},409);try{if(env.MEDIA)await env.MEDIA.delete(row.object_key)}catch{}await env.DB.prepare('DELETE FROM media WHERE id=?').bind(id).run();return json({ok:true})}
return json({ok:false,error:'Endpoint não encontrado.'},404)}

export { handleApi, ensureSchema };
